export const AUTH_SET = 'AUTH_SET';
export const TAG_DRAWER_TOGGLE = 'TAG_DRAWER_TOGGLE';
export const REVISION_SELECT = 'REVISION_SELECT';
export const HIDE_REVISION_PANEL = 'HIDE_REVISION_PANEL';
export const SHOW_REVISION_PANEL = 'SHOW_REVISION_PANEL';
